import globals from "globals";
import pluginJs from "@eslint/js";

export default [
  {
    files: ["src/js/**/*.js"],
    ignores: ["src/js/lib/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        hljs: "readonly",
        marked: "readonly",
        DOMPurify: "readonly",
        switchGalleryTab: "readonly",
        skipHistory: "readonly",
        loadHighlightJS: "readonly",
        initializeDOMReferences: "readonly",
        initializeDefaultValues: "readonly",
        initializeAboutTab: "readonly",
        initializeModelSettings: "readonly",
        initializeConversationName: "readonly",
        setupEventListeners: "readonly",
        initializeServicesAndModels: "readonly",
        initializeToolCalling: "readonly",
        deleteTransaction: "readonly",
        genericPlaceholders: "readonly"
      }
    },
    rules: {
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-var": "error",
      "semi": ["error", "always"],
      "quotes": ["error", "double"],
      "indent": ["error", 2],
      "no-multiple-empty-lines": ["error", { "max": 1 }],
      "eol-last": ["error", "always"],
      "comma-dangle": ["error", "always-multiline"],
      "no-trailing-spaces": "error",
      "object-curly-spacing": ["error", "always"],
      "array-bracket-spacing": ["error", "never"],
      "space-in-parens": ["error", "never"],
      "space-before-blocks": "error",
      "keyword-spacing": "error",
      "key-spacing": "error",
      "no-multi-spaces": "error",
      
      "no-use-before-define": "off",
      "no-shadow": "off",
      "no-invalid-this": "off",
      "no-alert": "off",
      "no-sync": "off",
      "radix": "off",
      "consistent-return": "off",
      "no-return-assign": "off",
      "no-sequences": "off",
      "no-void": "off",
      "prefer-arrow-callback": "off",
      "require-await": "off",
      "no-empty-function": "off",
      "no-lonely-if": "off",
      "no-unreachable": "off",
      "no-undefined": "off",
      "brace-style": "off",
      "prefer-const": "off",
      "eqeqeq": "off",
      "no-useless-concat": "off",
      "prefer-spread": "off",
      "prefer-rest-params": "off",
      
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-with": "error",
      "no-proto": "error",
      "no-caller": "error",
      "no-extend-native": "error",
      "no-labels": "error",
      "no-loop-func": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-return-await": "error",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "rest-spread-spacing": "error",
      "template-curly-spacing": "error",
      "template-tag-spacing": "error",
      "yield-star-spacing": "error",
      "arrow-spacing": "error",
      "no-class-assign": "error",
      "no-confusing-arrow": "error",
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "error",
      "no-this-before-super": "error",
      "prefer-numeric-literals": "error",
      "require-yield": "error",
      "symbol-description": "error",
      "curly": "off",
      "no-throw-literal": "error",
      "no-implicit-coercion": "error"
    }
  }
];
